name: Deployment Pipeline

on:
  push:
    #paths-ignore:
    #  - '.github/**'
    branches: 
      - "devops"

env:
  ENVIRONMENT_NAME: ${{ fromJSON('{"develop":"dev", "qa":"qa", "main":"prod", "devops":"dev"}')[github.head_ref || github.ref_name ] }}
  IMAGE_NAME_API: landing_page

jobs:
  build-and-push: 
    runs-on: ubuntu-20.04

    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push
        uses: docker/build-push-action@v3
        with:
          file: .devops/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_API }}:latest, 
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_API }}:${{ env.ENVIRONMENT_NAME }}_${{ github.run_number }}
          contex: .